#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@unblockmusic[-1]
	add ucitrack unblockmusic
	set ucitrack.@unblockmusic[-1].exec="/etc/init.d/unblockmusic restart"
	commit ucitrack

	delete firewall.unblockmusic
	set firewall.unblockmusic=include
	set firewall.unblockmusic.type=script
	set firewall.unblockmusic.path=/var/etc/unblockmusic.include
	set firewall.unblockmusic.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
